### ISSUE TITLE
FTB Chunks config is not detected

### ISSUE THREAD

**Issue by martymarty004** [Darkere/ServerConfigUpdater#2]
Hello,
this mod doesn't seem to recognise the new FTB Chunks serverconfig file (`ftbchunks.snbt`)

MC: `1.16.5`
ServerConfig Updater: [1.3](https://www.curseforge.com/minecraft/mc-mods/serverconfig-updater/files/3034936)
FTB Chunks: [ftb-chunks-forge-1605.3.2-build.91](https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge/files/3590598)

Output from logs:
`No ServerConfig for MODIDftbchunks found!`

**Comment by martymarty004** [comment]
I just found out that fixing this issue will not resolve my problem, since these .snbt files are not copied over from the `defaultconfig` folder in the first place.

This should be resolved by the [mod authors](https://github.com/FTBTeam/FTB-Mods-Issues/issues/69) (by using the default file type) because the [Forge Team](https://github.com/MinecraftForge/MinecraftForge/issues/6541) will not change the current behaviour.

**Comment by Darkere** [comment]
The forge issue you linked has nothing to do with it.

As far as I am aware. The ftb mods have recently updated to support copying from default configs. Unfortunately, since they don't use the normal forge config system my mod is unable to find their file and as such can't work with it.

**Comment by martymarty004** [comment]
OK, so *they* have to implement a way to let the packdevs update their player's already existing config, right?

**Comment by Darkere** [comment]
Yep.

**Comment by martymarty004** [comment]
OK, thanks for the clarification!
