### ISSUE TITLE
[1.20.1] serverconfigupdater is not a valid jar file.

### ISSUE THREAD

**Issue by Gbergz** [Darkere/ServerConfigUpdater#6]
Title^

![bild](https://github.com/Darkere/ServerConfigUpdater/assets/26634554/c80de76a-d85e-4ebc-b94e-a4392b3b09d9)

logs: https://gist.githubusercontent.com/Gbergz/fcc9c45010cfd3446788150a9095ac2b/raw/498e4184cb3610b26d8933ee97b81cdfacbd7319/gistfile1.txt

MC 1.20.1
Forge: 47.0.19

**Comment by Darkere** [comment]
I guess I should have checked that the automation I used actually worked...

**Comment by Darkere** [comment]
Fixed.. I'll Archive the broken version when curseforge stops throwing errors.

**Comment by Gbergz** [comment]
Thanks!
